# Generated by Django 3.0.4 on 2020-05-20 04:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='考试题')),
                ('answer', tinymce.models.HTMLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
