# Generated by Django 3.0.4 on 2020-05-20 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '阶段',
                'verbose_name_plural': '阶段',
            },
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '试题', 'verbose_name_plural': '试题'},
        ),
        migrations.AddField(
            model_name='case',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caseapp.Path'),
        ),
    ]
